### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by katychuang** [DataMascara/mimo_cat#1]
Change the heading on the page from "Minimum Movement Catalog" to "Minimum Movement"

**Comment by Jwright707** [comment]
I would like to work on this issue 😀

**Comment by Jwright707** [comment]
Also, just to make sure, is this change applying to every instance where the text "Minimum Movement Catalog" exist? For example, the 404.html, login.js, about.js, and index.html all have that text. I can change all instances to Minimum Movement if that's correct 👍

**Comment by katychuang** [comment]
Yup, that sounds about right. Go for it

**Comment by Jwright707** [comment]
Thank you, just created a PR.
